[workspace]
resolver = "3"
members = ["crates/cfglib"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/napbat/cfglib"
authors = ["coconutbird"]
rust-version = "1.99"
keywords = ["graphs", "control-flow", "compiler", "code-intelligence", "dataflow"]
categories = ["compilers", "no-std"]

[workspace.dependencies]
cfglib = { version = "0.1.0", path = "crates/cfglib" }
serde = { version = "1.0.228", default-features = false, features = ["derive", "alloc"] }
smallvec = { version = "1.15.1", default-features = false }

[workspace.lints.rust]
warnings = { level = "deny", priority = -2 }
unused = { level = "deny", priority = -1 }
nonstandard_style = { level = "deny", priority = -1 }
rust_2018_idioms = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }
unexpected_cfgs = { level = "deny", check-cfg = ['cfg(cfglib_bench_alloc)'] }

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

[workspace.lints.rustdoc]
all = { level = "deny", priority = -1 }
