[package]
name = "cfglib"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Generic no_std graph and dataflow framework for code intelligence and program analysis"
readme = "../../README.md"

[lints]
workspace = true

[features]
default = []
serde = ["dep:serde", "smallvec/serde"]

[dependencies]
serde = { workspace = true, optional = true }
smallvec.workspace = true

[[bench]]
name = "performance"
harness = false
